version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    ports:
    - 5000:5000
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
    - api
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    hostname: grafana
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
