---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data: 
  prometheus.yml: |
    global:
      scrape_interval: 1s
      evaluation_interval: 1s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:

    rule_files:

    scrape_configs:

      - job_name: "flask_metrics"

        static_configs:
        - targets: ["service-api:5000"]


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: my-test-mission
    env: prod
    owner: OznobMihail
spec:
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: "config"
              mountPath: "/etc/prometheus/prometheus.yml"
              subPath: "prometheus.yml"
      restartPolicy: Always
      volumes:
        - name: "config"
          configMap:
            name: "config"

---
apiVersion: v1
kind: Service
metadata:
  name: service-prometheus
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector: 
    app: prometheus-server
  sessionAffinity: None
  type: ClusterIP